name: Build Miatoll Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_kernel:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Update & install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison flex zip curl python3 unzip wget git \
            ccache libhiredis0.14 libncurses5-dev libncursesw5-dev libssl-dev

      - name: Prepare toolchains
        run: |
          mkdir -p toolchains
          echo "PATH=$GITHUB_WORKSPACE/toolchains/clang/bin:$GITHUB_WORKSPACE/toolchains/gcc64/bin:$GITHUB_WORKSPACE/toolchains/gcc32/bin:$PATH" >> $GITHUB_ENV

      - name: Clean previous build
        run: |
          cd kernel/out
          make mrproper

      - name: Configure kernel
        run: |
          cd kernel
          mkdir -p out
          cd out
          make O=$(pwd) ARCH=arm64 miatoll_defconfig

      - name: Build kernel Image.gz
        run: |
          cd kernel/out
          make -j$(nproc) O=$(pwd) ARCH=arm64 \
            Image.gz \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu-

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: miatoll_kernel
          path: kernel/out/arch/arm64/boot/Image.gz
